<a href="https://colab.research.google.com/github/Aleks-Data/HW-Python/blob/main/Python_DA_HW2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

1. Индексация массивов NumPy:


Напишите программу, которая:

- Запрашивает у пользователя ввод одномерного массива, элементы которого вводятся в виде чисел, разделенных пробелами.

- Преобразует введенную строку в массив NumPy.

- Запрашивает у пользователя индекс элемента, который необходимо извлечь из массива.

- Выводит значение элемента по запрошенному индексу.

- Запрашивает у пользователя ввод диапазона индексов в формате `начало:конец`, чтобы извлечь срез массива.

- Выводит срез массива.


Пример вывода:


Введите массив: 1 2 3 4 5

Введите индекс элемента: 2

Элемент с индексом 2: 3

Введите диапазон индексов (начало:конец): 1:4

Срез массива: [2 3 4]

In [9]:
a = np.array((input("Введите массив чисел через пробел: ")).split(), dtype = int)
n = int(input("Введите индекс элемента:"))
print(f"Элемент с индексом {n}:", a[n])

range = input("Введите диапазон индексов (начало:конец):")
start, end = map(int, range.split(':'))

print("Срез массива:", a[start:end])

Введите массив чисел через пробел: 1 2 3 4 5
Введите индекс элемента:3
Элемент с индексом 3: 4
Введите диапазон индексов (начало:конец):1:4
Срез массива: [2 3 4]


2. Операции с матрицами в NumPy:


Напишите программу, которая:

- Запрашивает у пользователя размеры матрицы MxN.

- Генерирует две матрицы указанных размеров, заполненные случайными числами от 0 до 9.

- Выводит обе сгенерированные матрицы на экран.

- Выполняет и выводит результат одной из следующих операций (на выбор пользователя): сложение матриц, умножение матриц, транспонирование одной из матриц.

- Если выбрано умножение, убедитесь, что размеры матриц соответствуют правилам матричного умножения.


Пример вывода:


Введите размеры матрицы MxN: 2x3


Первая матрица:

[[1 2 3]

 [4 5 6]]


Вторая матрица:

[[6 5 4]

 [3 2 1]]


Выберите операцию (сложение, умножение, транспонирование): сложение


Результат сложения:

[[ 7  7  7]

 [ 7  7  7]]



In [19]:
m, n = map(int, input("Введите размеры матрицы MxN через пробел:").split())

a = np.random.randint(0, 10, size = (m, n))
b = np.random.randint(0, 10, size = (m, n))

print("Первая матрица:\n", a)
print("Вторая матрица:\n", b)

operation = input("Выберите операцию (сложение, умножение):")

def result(operation, a, b):
    if operation == "сложение":
        return a + b
    elif operation == "умножение":
        if a.shape[1] == b.shape[0]:
            return np.dot(a, b)
        else:
            print("Неправильные размеры матриц")


print("Результат:\n", result(operation, a, b))


Введите размеры матрицы MxN через пробел:4 4
Первая матрица:
 [[1 3 4 6]
 [4 8 3 4]
 [4 7 7 6]
 [9 1 0 4]]
Вторая матрица:
 [[2 0 6 9]
 [8 0 2 9]
 [9 2 6 3]
 [1 3 3 0]]
Выберите операцию (сложение, умножение):умножение
Результат:
 [[ 68  26  54  48]
 [103  18  70 117]
 [133  32  98 120]
 [ 30  12  68  90]]
